import { Feather } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import React from "react";
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useColors } from "@/hooks/useColors";

type Section = { heading: string; body: string };
type Topic = {
  title: string;
  icon: React.ComponentProps<typeof Feather>["name"];
  intro: string;
  sections: Section[];
  footer?: string;
};

const TOPICS: Record<string, Topic> = {
  "what-data": {
    title: "What data we hold",
    icon: "eye",
    intro: "Here's exactly what Align stores on your behalf, why we need it, and how long we keep it.",
    sections: [
      { heading: "Account & balances", body: "Read-only balances and metadata from your linked institutions, refreshed via Plaid every few minutes." },
      { heading: "Transactions (12 months)", body: "Merchant, amount, date, category. Used to power your spending insights and alignment score." },
      { heading: "Goal & profile data", body: "The goals, target dates, risk profile, and preferences you've entered. Stored encrypted at rest." },
      { heading: "Device & session info", body: "Device model, OS, and login timestamps for security monitoring." },
    ],
    footer: "We never see or store your bank credentials. All institution access goes through Plaid's tokenized link.",
  },
  "export-data": {
    title: "Export my data",
    icon: "download",
    intro: "Request a complete copy of your Align data. We'll email a download link to sarah.chen@email.com within 24 hours.",
    sections: [
      { heading: "Included in the export", body: "All goals, transactions, account snapshots, alignment scores, alerts, and your full preference history." },
      { heading: "Format", body: "A single .zip containing JSON files for programmatic use plus a human-readable PDF summary." },
      { heading: "Frequency", body: "You can request an export once every 30 days. Older exports remain downloadable for 7 days." },
    ],
  },
  "privacy-policy": {
    title: "Privacy policy",
    icon: "book-open",
    intro: "Plain-language summary, last updated April 2026. The full legal version is available at align.app/privacy.",
    sections: [
      { heading: "What we collect", body: "Only what's needed to run Align: linked account data, your goals and preferences, and basic device info." },
      { heading: "How we use it", body: "To compute your alignment score, surface insights, and improve product quality. Never to sell to third parties." },
      { heading: "Who we share with", body: "Plaid (account aggregation) and AWS (hosting). Both bound by SOC 2 contracts. No advertising partners. Ever." },
      { heading: "Your rights", body: "Access, export, correct, or delete your data at any time from this Profile screen." },
    ],
  },
  "alignment-methodology": {
    title: "Goal Alignment methodology",
    icon: "book",
    intro: "Your Goal Alignment Score is a 0–100 measure of how well your day-to-day money behavior matches the goals you've set.",
    sections: [
      { heading: "Savings (0–30)", body: "Are you saving at the pace your goals require? Calculated from net monthly contributions vs. target." },
      { heading: "Spending (0–30)", body: "Is your spending leaving room for those contributions? Compares discretionary spend to your aligned budget." },
      { heading: "Investing (0–20)", body: "Is invested money allocated in line with your time horizon and risk profile?" },
      { heading: "Debt (0–20)", body: "Are debt balances trending in the right direction relative to your goal timeline?" },
    ],
    footer: "We refresh the score nightly. Educational reference, not personalized investment advice.",
  },
  "ai-guidance": {
    title: "How AI guidance works",
    icon: "cpu",
    intro: "Align uses on-device heuristics plus a server-side language model to draft suggestions. You always have the final call.",
    sections: [
      { heading: "What's local", body: "Score computation, drift detection, and category trends run entirely on your device." },
      { heading: "What's server-side", body: "Plain-language framing of suggestions (e.g. \"Move $4,200 into your Emergency Fund\") is generated by an LLM running in our private VPC." },
      { heading: "Privacy", body: "Only aggregated, de-identified signals are sent to the LLM — never raw transactions or merchant names." },
      { heading: "Your controls", body: "Disable anonymized ML training in Privacy & Data to opt out of model improvement." },
    ],
  },
  "security": {
    title: "Security practices",
    icon: "shield",
    intro: "Security is the floor, not a feature. Here's how Align protects your data.",
    sections: [
      { heading: "Encryption", body: "AES-256 at rest, TLS 1.3 in transit. Backups are encrypted with a separate key set." },
      { heading: "Authentication", body: "Email + biometric on device. Optional hardware key support. Sessions expire after 14 days of inactivity." },
      { heading: "Account access", body: "We use Plaid's tokenized link — your bank credentials never reach our servers." },
      { heading: "Audits", body: "Annual SOC 2 Type II audit. Quarterly penetration testing by an independent firm." },
    ],
    footer: "Report a security issue: security@align.app · PGP key on align.app/security",
  },
  "support": {
    title: "Support",
    icon: "help-circle",
    intro: "We're here Monday to Friday, 9am–6pm ET. Most questions are answered within a few hours.",
    sections: [
      { heading: "Email us", body: "support@align.app — best for billing, account access, or detailed questions. Average reply: 4 hours." },
      { heading: "Live chat", body: "Tap the chat bubble in the app between 9am and 6pm ET for instant help." },
      { heading: "Help center", body: "Browse 200+ guides at help.align.app, including step-by-step walkthroughs and goal templates." },
      { heading: "Status page", body: "Real-time uptime and incident history at status.align.app." },
    ],
  },
};

export default function InfoDetailScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const params = useLocalSearchParams<{ topic?: string }>();

  const topic = TOPICS[params.topic ?? ""] ?? TOPICS["privacy-policy"];

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={[styles.header, { paddingTop: insets.top + 12, borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.iconBtn}>
          <Feather name="x" size={22} color={colors.navy} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.navy }]} numberOfLines={1}>
          {topic.title}
        </Text>
        <View style={styles.iconBtn} />
      </View>

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={{ padding: 20, paddingBottom: insets.bottom + 60 }}
        showsVerticalScrollIndicator={false}
      >
        <View style={[styles.heroCard, { backgroundColor: colors.navy }]}>
          <View style={[styles.heroIcon, { backgroundColor: "rgba(178,223,219,0.18)" }]}>
            <Feather name={topic.icon} size={20} color="#B2DFDB" />
          </View>
          <Text style={styles.heroTitle}>{topic.title}</Text>
          <Text style={styles.heroIntro}>{topic.intro}</Text>
        </View>

        {topic.sections.map((s) => (
          <View
            key={s.heading}
            style={[styles.sectionCard, { backgroundColor: colors.card, borderColor: colors.border }]}
          >
            <Text style={[styles.sectionHeading, { color: colors.navy }]}>{s.heading}</Text>
            <Text style={[styles.sectionBody, { color: colors.text }]}>{s.body}</Text>
          </View>
        ))}

        {topic.footer && (
          <View style={[styles.footerCard, { backgroundColor: "#EBF8F8" }]}>
            <Feather name="info" size={14} color={colors.primary} />
            <Text style={[styles.footerText, { color: colors.navy }]}>{topic.footer}</Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 17, fontWeight: "700", flex: 1, textAlign: "center" },
  iconBtn: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  heroCard: { borderRadius: 16, padding: 20, marginBottom: 18 },
  heroIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  heroTitle: { color: "#fff", fontSize: 22, fontWeight: "700", marginBottom: 8 },
  heroIntro: { color: "#B2DFDB", fontSize: 14, lineHeight: 20 },
  sectionCard: { borderRadius: 12, borderWidth: 1, padding: 16, marginBottom: 10 },
  sectionHeading: { fontSize: 14, fontWeight: "700", marginBottom: 6 },
  sectionBody: { fontSize: 13, lineHeight: 19 },
  footerCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
  },
  footerText: { flex: 1, fontSize: 12, lineHeight: 17 },
});
